const creators = [
  {
    id: 1,
    name: 'John Doe',
    image: 'https://th.bing.com/th/id/OIP.mGcmaPrseO1StqjinTtGwwHaHN?rs=1&pid=ImgDetMain',
    socialMedia: '@johndoe_tech',
    platform: 'YouTube',
    followers: '100k',
    reviews: '4.8/5 (2.3k reviews)',
    bio: 'Specializes in tech reviews and gadget unboxings. Engages with a large audience of tech enthusiasts.',
    contact: 'johndoe@example.com',
    phone: '+1-555-0101',
    rating: 5, // out of 5
    highlights: ['Tech Reviews', 'Gadget Unboxings', 'Engagement with Audience']
  },
  {
    id: 2,
    name: 'Jane Smith',
    image: 'https://ilarge.lisimg.com/image/25103093/740full-laura-vergara.jpg',
    socialMedia: '@janesmith_fashion',
    platform: 'Instagram',
    followers: '250k',
    reviews: '4.9/5 (1.8k reviews)',
    bio: 'Fashion influencer showcasing the latest trends in sustainable clothing and eco-friendly fashion.',
    contact: 'janesmith@example.com',
    phone: '+1-555-0102',
    rating: 5,
    highlights: ['Sustainable Fashion', 'Eco-Friendly Tips', 'Style Guides']
  },
  {
    id: 3,
    name: 'Michael Johnson',
    image: 'https://static.wixstatic.com/media/9c4080_2660137735bc4e2e84ca2288fe949b71~mv2.jpg/v1/fill/w_630,h_850,al_c,q_85/9c4080_2660137735bc4e2e84ca2288fe949b71~mv2.jpg',
    socialMedia: '@mikej_fit',
    platform: 'TikTok',
    followers: '500k',
    reviews: '4.7/5 (3.1k reviews)',
    bio: 'Fitness expert and lifestyle influencer sharing workout routines and motivational content.',
    contact: 'mikej@example.com',
    phone: '+1-555-0103',
    rating: 4,
    highlights: ['Workout Routines', 'Motivational Content', 'Healthy Lifestyle Tips']
  },
  {
    id: 4,
    name: 'Emily Davis',
    image: 'https://media.istockphoto.com/id/1175528185/photo/young-indian-woman-live-vlogging-art-tutorial.jpg?s=612x612&w=0&k=20&c=uOm8wCSpnYgoUrKhP7F8kMzIB75-m1xEBtfYrsActPM=',
    socialMedia: '@emilyd_art',
    platform: 'YouTube',
    followers: '75k',
    reviews: '4.6/5 (980 reviews)',
    bio: 'Content creator focusing on art tutorials and creative DIY projects with a strong community of aspiring artists.',
    contact: 'emilyd@example.com',
    phone: '+1-555-0104',
    rating: 4,
    highlights: ['Art Tutorials', 'DIY Projects', 'Creative Community Engagement']
  },
  {
    id: 5,
    name: 'Chris Lee',
    image: 'https://backcountrymagazine.com/wp-content/uploads/2017/12/creary_embed__2_2018.jpg',
    socialMedia: '@chrislee_photography',
    platform: 'Instagram',
    followers: '120k',
    reviews: '4.8/5 (1.2k reviews)',
    bio: 'Renowned photographer sharing tips, behind-the-scenes content, and stunning visuals from around the world.',
    contact: 'chrislee@example.com',
    phone: '+1-555-0105',
    rating: 5,
    highlights: ['Photography Tips', 'Behind-the-Scenes', 'Travel Photography']
  },
  {
    id: 6,
    name: 'Anna Williams',
    image: 'https://th.bing.com/th/id/OIP.JT8n1jbf0LazFfLzNm-mOAHaHa?w=400&h=400&rs=1&pid=ImgDetMain',
    socialMedia: '@annaw_cooking',
    platform: 'YouTube',
    followers: '220k',
    reviews: '4.9/5 (5k reviews)',
    bio: 'Cooking expert sharing recipes, cooking tips, and meal prep guides to a large audience of food lovers.',
    contact: 'annaw@example.com',
    phone: '+1-555-0106',
    rating: 5,
    highlights: ['Recipe Tutorials', 'Meal Prep', 'Cooking Tips']
  },
  {
    id: 7,
    name: 'David Brown',
    image: 'https://earthnworld.com/wp-content/uploads/2022/08/Travel-Vlogger.jpg',
    socialMedia: '@davidbrown_travel',
    platform: 'YouTube',
    followers: '350k',
    reviews: '4.8/5 (4.1k reviews)',
    bio: 'Travel vlogger capturing adventures and offering travel tips to inspire exploration across the globe.',
    contact: 'davidbrown@example.com',
    phone: '+1-555-0107',
    rating: 4,
    highlights: ['Travel Tips', 'Adventure Vlogs', 'Cultural Experiences']
  },
  {
    id: 8,
    name: 'Megan Wilson',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu0NrFr2jjok94LVavH9HF3dDCTRzlgJ_VFQ&s',
    socialMedia: '@meganwilson_lifestyle',
    platform: 'Instagram',
    followers: '180k',
    reviews: '4.7/5 (2.5k reviews)',
    bio: 'Lifestyle influencer focusing on wellness, productivity, and minimalism.',
    contact: 'meganwilson@example.com',
    phone: '+1-555-0108',
    rating: 4,
    highlights: ['Wellness', 'Productivity Tips', 'Minimalism']
  },
  {
    id: 9,
    name: 'Sophie Turner',
    image: 'https://media.glamour.com/photos/60b93d3dde86dd3d3ae61757/master/w_2560%2Cc_limit/sophie-turner.jpg',
    socialMedia: '@sophiet_creative',
    platform: 'Pinterest',
    followers: '300k',
    reviews: '4.8/5 (3.5k reviews)',
    bio: 'Creative designer sharing inspiring home decor and DIY projects to elevate your space.',
    contact: 'sophiet@example.com',
    phone: '+1-555-0109',
    rating: 5,
    highlights: ['Home Decor', 'DIY Projects', 'Creative Inspiration']
  },
  {
    id: 10,
    name: 'Olivia Parker',
    image: 'https://www.rismedia.com/wp-content/uploads/2022/01/1933_gallery.jpg',
    socialMedia: '@oliviap_fitness',
    platform: 'Instagram',
    followers: '150k',
    reviews: '4.9/5 (1.1k reviews)',
    bio: 'Fitness coach dedicated to helping others achieve their health goals through exercise and nutrition.',
    contact: 'oliviap@example.com',
    phone: '+1-555-0110',
    rating: 5,
    highlights: ['Fitness Coaching', 'Nutrition Advice', 'Health Tips']
  },
  {
    id: 11,
    name: 'Ava Green',
    image: 'https://th.bing.com/th/id/OIP.uG7pBeInsNAbmiU9u-8GNAHaJw?rs=1&pid=ImgDetMain',
    socialMedia: '@avagreen',
    platform: 'LinkedIn',
    followers: '80k',
    reviews: '4.7/5 (900 reviews)',
    bio: 'Business consultant providing insights on entrepreneurship and small business growth.',
    contact: 'avagreen@example.com',
    phone: '+1-555-0111',
    rating: 4,
    highlights: ['Entrepreneurship', 'Business Growth', 'Consulting']
  },
  {
    id: 12,
    name: 'Lily Evans',
    image: 'https://th.bing.com/th/id/OIP.64uH4Ciurq15XRAUTkQZdgHaDg?rs=1&pid=ImgDetMain',
    socialMedia: '@lilyevans',
    platform: 'YouTube',
    followers: '200k',
    reviews: '4.8/5 (1.5k reviews)',
    bio: 'DIY and crafting expert sharing easy projects for home and gifts.',
    contact: 'lilyevans@example.com',
    phone: '+1-555-0112',
    rating: 5,
    highlights: ['DIY Projects', 'Creative Inspiration', 'Crafting']
  },
];

export default creators;
